AplicacionWeb/Models/Sucursal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sucursal()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDSUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHAAPERTURA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

AplicacionWeb/Controllers/SucursalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AplicacionWeb.Models;

namespace AplicacionWeb.Controllers
{
    public class SucursalController : Controller
    {
        // GET: Sucursal
        public ActionResult Index()
        {
            List<SucursalCLS> listaSucursal = null;

            using (var db = new BDPasajeEntities())
            {
                listaSucursal = (from Sucursal in db.Sucursal
                                 where Sucursal.BHABILITADO == 1
                                 select new SucursalCLS
                                 {
                                     idsucursal = Sucursal.IIDSUCURSAL,
                                     nombre = Sucursal.NOMBRE,
                                     telefono = Sucursal.TELEFONO,
                                     email = Sucursal.EMAIL
                                 }).ToList();
            }

            return View(listaSucursal);
        }

        public ActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Agregar(SucursalCLS oSucursalCLS)
        {
            if (ModelState.IsValid)
            {
                using (var db = new BDPasajeEntities())
                {
                    Sucursal oSucursal = new Sucursal();
                    oSucursal.NOMBRE = oSucursalCLS.nombre;
                    oSucursal.DIRECCION = oSucursalCLS.direccion;
                    oSucursal.TELEFONO = oSucursalCLS.telefono;
                    oSucursal.EMAIL = oSucursalCLS.email;
                    oSucursal.FECHAAPERTURA = oSucursalCLS.fechaApertura;
                    oSucursal.BHABILITADO = 1;

                    db.Sucursal.Add(oSucursal);
                    db.SaveChanges();
                }
            }
            else
            {
                return View(oSucursalCLS);
            }

            return RedirectToAction("Index");
        }
    }
}

AplicacionWeb/Views/Sucursal/Agregar.cshtml
@using AplicacionWeb.Models

@model SucursalCLS

@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Sucursal", FormMethod.Post))
        {
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.direccion)
                @Html.TextBoxFor(p => p.direccion, new { @class = "form-control" })
                @Html.ValidationMessage("direccion", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.telefono)
                @Html.TextBoxFor(p => p.telefono, new { @class = "form-control" })
                @Html.ValidationMessage("telefono", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.email)
                @Html.TextBoxFor(p => p.email, new { @class = "form-control" })
                @Html.ValidationMessage("email", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.fechaApertura)
                @Html.EditorFor(p => p.fechaApertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("fechaApertura", new { @class = "text-danger" })
            </div>
            <br />
            <div style="margin:auto">
                <input type="submit" class="btn btn-primary" value="Guardar" />
            </div>
        }
    </div>
</div>

AplicacionWeb/Views/Sucursal/Index.cshtml
@using AplicacionWeb.Models

@model List<SucursalCLS>


@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Agregar", "Agregar", "Sucursal", null, new { @class = "btn btn-primary" })

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td width="10%">@Html.LabelFor(p => Model[0].idsucursal)</td>
            <td width="30%">@Html.LabelFor(p => Model[0].nombre)</td>
            <td width="60%">@Html.LabelFor(p => Model[0].telefono)</td>
            <td width="60%">@Html.LabelFor(p => Model[0].email)</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.idsucursal</td>
                <td>@item.nombre</td>
                <td>@item.telefono</td>
                <td>@item.email</td>
            </tr>
        }
    </tbody>
</table>