AplicacionWeb/Models/Marca.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marca()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDMARCA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

AplicacionWeb/Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AplicacionWeb.Models;

namespace AplicacionWeb.Controllers
{
    public class MarcaController : Controller
    {
        // GET: Marca
        public ActionResult Index()
        {
            List<MarcaCLS> listaMarca = null;

            using (var db = new BDPasajeEntities())
            {
                listaMarca = (from Marca in db.Marca
                              where Marca.BHABILITADO == 1
                              select new MarcaCLS
                              {
                                  idmarca = Marca.IIDMARCA,
                                  nombre = Marca.NOMBRE,
                                  descripcion = Marca.DESCRIPCION
                              }).ToList();
            }

            return View(listaMarca);
        }

        public ActionResult Agregar() 
        {
            return View();
        }

        [HttpPost]
        public ActionResult Agregar(MarcaCLS oMarcaCLS)
        {
            if (ModelState.IsValid)
            {
                using (var db = new BDPasajeEntities())
                {
                    Marca oMarca = new Marca();
                    oMarca.NOMBRE = oMarcaCLS.nombre;
                    oMarca.DESCRIPCION = oMarcaCLS.descripcion;
                    oMarca.BHABILITADO = 1;

                    db.Marca.Add(oMarca);
                    db.SaveChanges();
                }
            }
            else
            {
                return View(oMarcaCLS);
            }

            return RedirectToAction("Index");
        }
    }
}

AplicacionWeb/Views/Marca/Agregar.cshtml
@using AplicacionWeb.Models

@model MarcaCLS

@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Marca", FormMethod.Post))
        {
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.descripcion)
                @Html.TextBoxFor(p => p.descripcion, new { @class = "form-control" })
                @Html.ValidationMessage("descripcion", new { @class = "text-danger" })
            </div>
            <br />
            <div style="margin:auto">
                <input type="submit" class="btn btn-primary" value="Guardar" />
            </div>
        }
    </div>
</div>

AplicacionWeb/Views/Marca/Index.cshtml
@using AplicacionWeb.Models 

@model List<MarcaCLS>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Agregar", "Agregar", "Marca", null, new { @class = "btn btn-primary" })

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            @*<td width="10%">Id Marca</td>
            <td width="30%">Nombre</td>
            <td width="60%">Descripcion</td>*@
            <td width="10%">@Html.LabelFor(p => Model[0].idmarca)</td>
            <td width="30%">@Html.LabelFor(p => Model[0].nombre)</td>
            <td width="60%">@Html.LabelFor(p => Model[0].descripcion)</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.idmarca</td>
            <td>@item.nombre</td>
            <td>@item.descripcion</td>
        </tr>
        }
    </tbody>
</table>